on: [push]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Compose Up
        run: docker-compose up -d
      - name: Test
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests
      - name: Compose Down
        run: docker-compose down --remove-orphans