on:
  push:
    branch: [ master ]
  pull-request:
    branch: [ master ]

jobs:
  build-test-push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      DB: postgresql
      DB_NAME: pktapi_db
      DB_USER: postgres
      DB_PSWD: 123456789
      DB_HOST: localhost
      DB_PORT: 5432
      SECRET_KEY: testing-key

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u atoivat -p DOCKER_PASSWORD
      - name: Docker Build
        run: docker build . -t atoivat/pktapi:$(date +%s)
      - name: Compose Up
        run: docker-compose up -d
      - name: Test
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests
      - name: Compose Down
        run: docker-compose down --remove-orphans
      - name: Docker Push
        run: docker push atoivat/pktapi